#### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


In [46]:
import numpy as np

vector = np.arange(1, 11)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [43]:
A = np.zeros((3, 3), dtype=int)
A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [42]:
A = np.random.randint(1, 10, (5, 5))
A

array([[6, 4, 3, 8, 8],
       [3, 6, 8, 6, 6],
       [8, 2, 2, 8, 7],
       [4, 7, 1, 3, 2],
       [7, 2, 3, 9, 9]])

#### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [14]:
A = np.random.rand(4, 4)
A

array([[0.20789093, 0.58801249, 0.6060514 , 0.5181521 ],
       [0.93665992, 0.2120535 , 0.70705348, 0.57893308],
       [0.87993982, 0.35037878, 0.06803882, 0.65522329],
       [0.97583495, 0.67850774, 0.7850976 , 0.66130808]])

#### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [21]:
vector_1 = np.random.randint(1, 11, (5))
vector_2 = np.random.randint(1, 11, (5))


plus = vector_1+vector_2
minus = vector_1-vector_2
mul = vector_1*vector_2

vector_1, vector_2, plus, minus, mul

(array([8, 3, 8, 4, 3]),
 array([10,  1,  3,  6,  9]),
 array([18,  4, 11, 10, 12]),
 array([-2,  2,  5, -2, -6]),
 array([80,  3, 24, 24, 27]))

#### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [41]:
vector_1 = np.random.randint(1, 10, (7))
vector_2 = np.random.randint(1, 10, (7))

dot_product = vector_1@vector_2
dot_product_1 = np.dot(vector_1, vector_2)

dot_product, dot_product_1

(179, 179)

#### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [39]:
matrix_A = np.random.randint(1, 11, (2, 2), dtype=int)
matrix_B = np.random.randint(1, 11, (2, 3), dtype=int)

mul = matrix_A@matrix_B
mul, matrix_A, matrix_B

(array([[35, 36, 30],
        [77, 86, 66]]),
 array([[ 2,  3],
        [ 1, 10]]),
 array([[7, 6, 6],
        [7, 8, 6]]))

#### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [49]:

M = np.random.randint(1, 11, (3, 3))

inverse_M = np.linalg.inv(M)
inverse_M

array([[ 1.53846154e-01, -2.21153846e-01,  2.88461538e-02],
       [-4.22367455e-18,  1.56250000e-01, -3.12500000e-02],
       [-7.69230769e-02, -1.44230769e-02,  1.10576923e-01]])

#### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [55]:
M = np.random.rand(4, 4)

T = M.T
M, T

(array([[0.66045285, 0.92805371, 0.20245912, 0.77419013],
        [0.49616584, 0.61237243, 0.40024607, 0.63922756],
        [0.01019154, 0.2640525 , 0.19816147, 0.05269246],
        [0.0516648 , 0.37997896, 0.79394354, 0.54690132]]),
 array([[0.66045285, 0.49616584, 0.01019154, 0.0516648 ],
        [0.92805371, 0.61237243, 0.2640525 , 0.37997896],
        [0.20245912, 0.40024607, 0.19816147, 0.79394354],
        [0.77419013, 0.63922756, 0.05269246, 0.54690132]]))

#### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [56]:
M = np.random.randint(1, 11, (3, 4))
v = np.random.randint(1, 11, (4))

M@v

array([107, 154, 148])

#### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [57]:
M = np.random.rand(2, 3)
v = np.random.rand(3)

M@v

array([0.73915127, 0.39982638])

#### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [60]:
M = np.random.randint(1, 11, (2, 2))
V = np.random.randint(1, 11, (2, 2))

M*V

(array([[64, 45],
        [ 2, 56]]),
 array([[ 73, 103],
        [ 24,  66]]))

#### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [62]:
M = np.random.randint(1, 11, (2, 2))
V = np.random.randint(1, 11, (2, 2))

M@V

array([[10, 14],
       [23, 43]])

#### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [63]:
M = np.random.randint(1, 101, (5, 5))

sum_matrix = np.sum(M)
sum_matrix

1177

#### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [66]:
M = np.random.randint(1, 11, (4, 4))
V = np.random.randint(1, 11, (4, 4))

M-V

array([[-4, -4,  4, -4],
       [-1,  0,  5, -5],
       [-1, -8, -3,  0],
       [ 1,  6, -2, -3]])

#### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [79]:
M = np.random.rand(3, 3)

row_sum = np.sum(M, axis=1)

vector_sum = row_sum.reshape(-1, 1)
vector_sum

array([[1.64717683],
       [1.26495492],
       [0.91477589]])

#### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [82]:
M = np.random.randint(1, 11, (3, 4))

squared_matrix = M**2

squared_matrix

array([[36, 49, 36,  9],
       [49, 16,  9, 49],
       [49, 81, 64, 81]])

#### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [86]:
M = np.random.randint(1, 51, (4))

M_sqrt = np.sqrt(M)
M_sqrt

array([4.12310563, 5.47722558, 6.4807407 , 6.8556546 ])